Repository umng/dailyx-store, pull requests merged in 2020-10, with the labels that each got.

#2 About Us.html
  About us.html
Labels: hacktoberfest-accepted

#4 Updated Homepage with new design
  assets/images/favicon.png
  assets/images/logo.png
  assets/style/style.css
  index.html
Labels: hacktoberfest

#6 Contact Us.html
  Contact Us.html
  favicon.png
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added logo About Us.html
  About us.html
Labels: hacktoberfest, hacktoberfest-accepted

#8 Develop
  contact-us.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#10 Updated Privacy page
  privacy-policy.html
Labels: hacktoberfest, hacktoberfest-accepted

#11 updated page
  privacy-policy.html
Labels: hacktoberfest, hacktoberfest-accepted

#12 updated privacy policy page
  privacy-policy.html
Labels: hacktoberfest, hacktoberfest-accepted

#13 updated privacy policy page
  privacy-policy.html
Labels: hacktoberfest, hacktoberfest-accepted
